printWidth: 100
semi: true
singleQuote: true
useTabs: false
tabWidth: 2
plugins:
  - '@ianvs/prettier-plugin-sort-imports'
importOrder:
  - '<BUILTIN_MODULES>'
  - '<THIRD_PARTY_MODULES>'
  - ''
  - '^@webpulse/(.*)$'
  - ''
  - '^#components/(.*)$'
  - '^#server/(.*)$'
  - '^#prisma/(.*)$'
  - '^#types/(.*)$'
  - '^#utils/(.*)$'
  - '^#constants/(.*)$'
  - ''
  - '^[./]'
importOrderTypeScriptVersion: 5.4.2
