version: '0.2'
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words: []
ignoreWords:
  - fastify
  - ianvs
  - kysely
  - kyselify
  - piku
  - pino
  - pkgroll
  - supabase
  - typebox
import: []
