version: '0.2'
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words: []
ignoreWords:
  - dotenvx
  - fastify
  - ianvs
  - kysely
  - kyselify
  - mantine
  - piku
  - pino
  - pkgroll
  - supabase
  - syncpack
  - typebox
  - webpulse
import: []
