version: '0.2'
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words: []
ignoreWords:
  - dotenvx
  - fastify
  - fontsource
  - ianvs
  - isbot
  - kysely
  - kyselify
  - lucide
  - mantine
  - outfile
  - piku
  - pino
  - pipeable
  - reduxjs
  - supabase
  - syncpack
  - typebox
  - webpulse
import: []
