services:
  client:
    image: pikuafk/webpulse.client
    env_file:
      - .env.prod
    container_name: webpulse.client
    build:
      context: .
      target: client
    ports:
      - 3000:3000

  server:
    image: pikuafk/webpulse.server
    env_file:
      - .env.prod
    container_name: webpulse.server
    build:
      context: .
      target: server
    ports:
      - 4000:4000
