services:
  webpulse:
    image: pikuafk/webpulse.server:0.0.0
    env_file:
      - .env.prod
    container_name: webpulse.server
    build:
      context: .
    ports:
      # - 3000:3000
      - 4000:4000
