services:
  server:
    image: pikuafk/webpulse.server
    env_file:
      - .env.prod
    container_name: webpulse.server
    build:
      context: .
      target: server
    ports:
      - 4000:4000
