app = "webpulse"
kill_signal = "SIGTERM"
kill_timeout = "10s"
primary_region = "bom"

[build]
build-target = "client"

[deploy]
strategy = "rolling"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 3_000
min_machines_running = 0
processes = [ "app" ]

  [[http_service.checks]]
  grace_period = "5s"
  interval = "24h0m0s"
  method = "GET"
  path = "/"
  timeout = "1m0s"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"
