name: deploy_server

on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
        with: 
          version: 0.2.59
      - run: fly deploy --config fly.server.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
